<?php
$title1 = "Четвёртое задание";
$content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed molestie nunc euismod ex consequat, sit amet commodo neque condimentum. Aenean pulvinar est ex, nec congue nibh molestie cursus. Integer pharetra erat id justo ornare maximus. Vestibulum accumsan in neque et vestibulum. Quisque pharetra et velit at commodo. Ut a nulla eu diam laoreet rutrum quis eget odio. Suspendisse ultricies sapien libero, vitae rhoncus nulla consequat auctor. Ut sit amet feugiat purus. Nulla in erat eu lorem laoreet viverra.
Suspendisse vitae libero a orci malesuada volutpat. Duis ullamcorper lacinia gravida. Mauris non elit id nisl iaculis volutpat. Vivamus mollis sapien et augue tempus, vel congue ante feugiat. Integer elementum eros felis. Vivamus dolor ex, euismod vitae velit condimentum, scelerisque volutpat enim. Proin quis ex sed mi dapibus aliquam. Nam eget congue est. Maecenas hendrerit mauris quam, at semper metus condimentum et. Vivamus volutpat facilisis nisi a mattis. Vestibulum viverra justo ac nunc efficitur, id pulvinar magna pretium. In lobortis magna sed nibh finibus ultrices. Maecenas gravida nec ligula in vulputate. Nulla at justo et turpis fermentum hendrerit a eu lacus. Quisque porta gravida urna, id luctus nunc pulvinar eget.
Nulla ornare felis in mauris feugiat pulvinar. Cras eleifend tellus id mi mattis, sed cursus ante posuere. Donec laoreet rutrum cursus. Ut sed cursus dolor. Nam elementum, massa a lobortis pretium, eros augue consequat tortor, in suscipit nisl elit eu velit. Aenean vulputate, nibh et maximus tincidunt, ex est fringilla mauris, nec dictum nisi velit non ante. Aliquam accumsan arcu non arcu consequat porttitor. Aenean facilisis lorem elementum lobortis maximus. Quisque aliquam nulla at convallis porta. Proin at neque ac nulla fermentum rhoncus. Donec nec justo nisi. Cras quis ligula ultrices, cursus orci at, convallis ex. Cras volutpat ligula dui. Nullam erat leo, placerat vel felis ut, tristique fringilla turpis. Praesent lectus est, congue vel euismod sed, pulvinar et leo. Quisque ac finibus ex.
Sed ut quam tempor, mollis ipsum nec, consectetur felis. Integer congue, massa non maximus dapibus, odio turpis ultrices sem, at sagittis ante magna ac nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque semper arcu id congue egestas. Aenean vulputate feugiat tristique. Suspendisse nec libero nibh. Phasellus vestibulum enim at ipsum lacinia gravida. Maecenas lectus enim, efficitur quis placerat lacinia, molestie id eros. Duis ultricies nulla ut turpis varius rutrum. Aenean nec risus sagittis, volutpat mi in, consequat leo.
Ut lorem nulla, consequat a diam eu, tincidunt tempus sem. Curabitur est nulla, maximus in maximus non, porttitor nec urna. Aenean rutrum metus in dictum facilisis. Curabitur dignissim elit velit, ut suscipit turpis feugiat in. Curabitur vel libero justo. Aliquam sed lectus sed ipsum elementum scelerisque. Sed in elementum felis, nec convallis augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam eget erat in odio hendrerit tempor quis cursus sem. Quisque tempor aliquam bibendum. Aliquam porttitor metus non turpis congue, a lobortis tortor laoreet. Donec a ligula augue. Etiam hendrerit eros nisl, vel dapibus magna maximus in.";
$curentYear = date("Y");

?>

<h1> <?php echo $title1 ?> </h1>
<p><?php echo "$content <br> <br> $curentYear" ?></p>
